language: objective-c
osx_image: xcode7.3
cache: cocoapods
rvm:
- 2.2
podfile: Sensorama/Podfile
script:
. cd Sensorama && xcrun xcodebuild -list -workspace ./Sensorama.xcworkspace
- cd Sensorama && scan --workspace Sensorama.xcworkspace --scheme SensoramaTests
- ./build.sh bootstrap
- ./build.sh
addons:
  ssh_known_hosts:
  - gitlab.com
