language: objective-c
osx_image: xcode7.3
cache: cocoapods
rvm:
- 2.2
podfile: Sensorama/Podfile
script:
- echo -en 'travis_fold:start:bootstrapping\r'
- echo -en 'travis_fold:begin:bootstrapping\r'
- ./build.sh bootstrap
- echo -en 'travis_fold:end:bootstrapping\r'
- cd Sensorama && xcrun xcodebuild -list -workspace ./Sensorama.xcworkspace
- cd Sensorama && scan --workspace Sensorama.xcworkspace --scheme SensoramaTests
- ./build.sh
addons:
  ssh_known_hosts:
  - gitlab.com
