language: objective-c
osx_image: xcode7.3
cache: cocoapods
rvm:
- 2.2.4

# HACK TO FIX:
# https://github.com/fastlane/fastlane/issues/6203
before_install:
  # Force bundler 1.12.5 because version 1.13 has issues, see https://github.com/fastlane/fastlane/issues/6065#issuecomment-246044617
  - gem uninstall bundler -v '>1.12.5' --force || echo "bundler >1.12.5 is not installed"
  - gem install bundler -v 1.12.5 --no-rdoc --no-ri --no-document --quiet

script:
#- gem update
#- gem install fastlane --pre
#- fastlane -v
#- scan -v
#- cd Sensorama && xcodebuild -list -workspace Sensorama.xcworkspace && cd ..
#- cd Sensorama && ../scripts/reproduce_test_issues
- ./scripts/travis_script.sh
#- ./scripts/script_with_folds
addons:
  ssh_known_hosts:
  - gitlab.com
